### ISSUE TITLE
sha256 mismatch 

### ISSUE THREAD

**Issue by kvorobyov** [DaniruKun/homebrew-ytarchive#1]
Getting the following error message when installing from brew:

Error: ytarchive: SHA256 mismatch
Expected: 29931b22d8cb22ff6aefd2f4601816eb5c3664ec88518f9da432e3d460549923
  Actual: 2bfd5137414a2881d87be51ea8331819365c1163bf90540e4341c67c873f8f07

**Comment by wulph111** [comment]
#metoo


any troubleshooting steps?

**Comment by jtheletter** [comment]
This issue persists.
