### ISSUE TITLE
SHA256 mismatch again

### ISSUE THREAD

**Issue by qchenac** [DaniruKun/homebrew-ytarchive#4]
`Error: ytarchive: SHA256 mismatch
Expected: f61ac9b3606476306c208dd87961a3ca846efa92eaad651fa0270293c13a54c2
  Actual: 8075ddb116f9a7e861fd7b318dfce3277dbebbdc8a8c2fcdf8f025d98c9a26a8`

**Comment by omerien** [comment]
#5 for a fix

**Comment by danirukun** [comment]
Closing as the formula is now moved to [HoloArchivists](https://github.com/HoloArchivists/homebrew-tap/blob/main/Formula/ytarchive.rb).
